[package]
name = "corrosion"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "emulator"
path = "src/emulator.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dyn_partial_eq = "0.1.2"
num_enum = "0.5.7"
sdl2 = "0.35.2"
